import Head from "next/head";
import Link from "next/link";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="w-full px-6 py-5">
          <h3 className="text-3xl m-0 text-center">Welcome</h3>
          <div className="w-[70%] mx-auto flex flex-row justify-between">
            <Link legacyBehavior href="/auth">
              Registration
            </Link>
            <Link legacyBehavior href="/auth/login">
              Login
            </Link>
          </div>
        </div>
      </main>
    </>
  );
}
